version: '3.8'

services:
  comfyui-bot:
    build: .
    container_name: comfyui-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # 持久化数据
      - ./data:/data
      # 如果需要修改工作流，可以挂载
      # - ./workflow.json:/app/workflow.json
    networks:
      - comfyui-network
    # 如果 ComfyUI 在同一个 docker-compose 中，可以使用服务名
    # 例如: COMFYUI_URL=http://comfyui:8188

networks:
  comfyui-network:
    driver: bridge
